name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.33.0-focal
      env:
         ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: test run
      run:
        echo "start the shopping app"
        ./shopping-store-linux-amd64 &
        echo "install dependencies"
        npm ci
        echo "run Playwright tests"
        npm run test:ci
